### ISSUE TITLE
MPSCNNConvolutionのinitがInvoke出来ません。

### ISSUE THREAD

**Issue by nenoNaninu** [shu223/iOS-10-Sampler#15]
現在研究室でiPhoneXを使いリアルタイムで画像処理をしたいということになり、このサンプルを見つけさせて頂きました。ありがとうございます。
そこでビルドをしたのですが、SlimMSCNN.swiftの88行目にて
```
Cannot invoke 'MPSCNNConvolution.init' with an argument list of type '(device: MTLDevice, convolutionDescriptor: MPSCNNConvolutionDescriptor, kernelWeights: UnsafePointer<Float>, biasTerms: UnsafePointer<Float>, flags: MPSCNNConvolutionFlags)'
```
といったエラーでビルドが失敗します。このプロジェクトは現在のXcode9,swift4で実行することは不可能なのでしょうか？もしくはios11ではできないのでしょうか？
よろしくお願いします。

**Comment by shu223** [comment]
Enabled work with Xcode 9.3, 9.4 / iOS 10. Please check it!
