### ISSUE TITLE
Metal Performance Shaders not Supported on iPhone 5S

### ISSUE THREAD

**Issue by catarino** [shu223/iOS-10-Sampler#3]
Digit and Object recognition crashes on my 5S stating "Metal Performance Shaders not Supported on current Device" but I haven't found any info on Apple and other forums stating this.

**Comment by shu223** [comment]
Thanks for reporting. I just fixed it. Unfortunately, 5s doesn't support MetalPerformanceShaders, however now it doesn't crash.

**Comment by catarino** [comment]
thanx @shu223 ! ;)

**Comment by erickingxu** [comment]
@shu223 , can you provide some official info about "Metal Performance Shaders not Supported on iPhone 5S"
I can't find apple gives some tips ,but iphone 5s should support Metal

**Comment by shu223** [comment]
@erickingxu 
https://developer.apple.com/metal/feature-sets/

**Comment by palxex** [comment]
@shu223 could I think it means only A8+ support MPS ?

**Comment by shu223** [comment]
@palxex yes, i thinks so: https://developer.apple.com/reference/metal/mtlfeatureset

**Comment by palxex** [comment]
Thanks.
