### ISSUE TITLE
Error: MetalPerformanceShaders is not supported on current device

### ISSUE THREAD

**Issue by tl67821102** [shu223/iOS-10-Sampler#7]
I used Iphone 5s to test "Image Recognition" and appear a error "not support this device". What can i do, tell me how to resolve with this. Thank you so much.

**Comment by shu223** [comment]
@tl67821102 
Sorry to be late to reply. The error message is the answer. 

Metal Performance Shaders framework is NOT supported on iPhone 5s. So, to resolve this, you can use another device such as iPhone 6, 6s, 7, or something it supports MPS.
